// <auto-generated />
using System;
using FortiScope.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortiScope.Data.Migrations
{
    [DbContext(typeof(FortiScopeDbContext))]
    [Migration("20260820130526_AddAlertSettings")]
    partial class AddAlertSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("FortiScope.Data.Entities.AlertSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuCriticalPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CpuWarningPercent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryCriticalPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MemoryWarningPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfflineTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AlertSettings", (string)null);
                });

            modelBuilder.Entity("FortiScope.Data.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivacyProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnmpUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SnmpVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FortiScope.Data.Entities.DeviceMetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Connected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CpuUsage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MemoryUsage")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SessionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceIp", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("DeviceMetricSamples");
                });

            modelBuilder.Entity("FortiScope.Data.Entities.InterfaceMetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<double>("IncomingMbps")
                        .HasColumnType("REAL");

                    b.Property<int>("InterfaceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InterfaceName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OutgoingMbps")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalMbps")
                        .HasColumnType("REAL");

                    b.Property<double?>("UtilizationPercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InterfaceIndex", "TimestampUtc");

                    b.HasIndex("DeviceIp", "InterfaceIndex", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("InterfaceMetricSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
